# Generated by Django 3.1.4 on 2020-12-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('batting_team', models.CharField(max_length=50)),
                ('batsman', models.CharField(max_length=50)),
                ('batsman_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('first_officiated', models.IntegerField()),
                ('last_officiated', models.IntegerField()),
                ('Number_of_Matches', models.IntegerField()),
            ],
        ),
    ]
